# Generated by Django 2.2.12 on 2021-08-06 17:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_VhFhH10', '0002_auto_20210719_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='neighbors_id_set',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='neighbors_opinion_set',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
