# Generated by Django 2.2.12 on 2022-02-03 03:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_FmH10', '0002_player_total_payoff_experiment_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='model_payoff_round',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
