# Generated by Django 2.2.12 on 2021-06-26 06:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='question1',
        ),
        migrations.AddField(
            model_name='player',
            name='quiz_answer',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
