# Generated by Django 2.2.12 on 2021-06-26 07:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210625_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='quiz_answer',
        ),
        migrations.AddField(
            model_name='player',
            name='answer',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
