# Generated by Django 2.2.12 on 2021-06-26 05:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_vhfmh0_group', to='otree.Session')),
            ],
            options={
                'db_table': 'game_VhFmH0_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_vhfmh0_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'game_VhFmH0_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('initial_opinion', otree.db.models.FloatField(null=True)),
                ('opinion_last_round', otree.db.models.FloatField(null=True)),
                ('opinion_this_round', otree.db.models.FloatField(help_text='Note: please fill in a number between 0 and 1', null=True, verbose_name='Please update your opinion in this round')),
                ('observed_opinion_player1', otree.db.models.FloatField(null=True)),
                ('observed_opinion_player2', otree.db.models.FloatField(null=True)),
                ('observed_id_player1', otree.db.models.IntegerField(null=True)),
                ('observed_id_player2', otree.db.models.IntegerField(null=True)),
                ('if_connect_player1', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 1?')),
                ('if_connect_player2', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 2?')),
                ('num_neighbors', otree.db.models.IntegerField(default=0, null=True)),
                ('disconnect_with_player1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('disconnect_with_player2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('if_miss_neighbor', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True)),
                ('if_miss_opinion', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_VhFmH0.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_vhfmh0_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_vhfmh0_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_VhFmH0.Subsession')),
            ],
            options={
                'db_table': 'game_VhFmH0_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_VhFmH0.Subsession'),
        ),
    ]
