# Generated by Django 2.2.12 on 2022-01-24 22:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_practice_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_1',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_2',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_3',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_4',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_5',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_6',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_7',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_neighbor_opinion_8',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
    ]
