# Generated by Django 2.2.12 on 2022-02-02 22:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_practice_game', '0003_auto_20220124_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='payoff_under_slider',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
