# Generated by Django 2.2.12 on 2022-02-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_practice_game', '0004_player_payoff_under_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payoff_under_slider',
        ),
    ]
