# Generated by Django 2.2.12 on 2022-02-03 02:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_practice_game', '0005_remove_player_payoff_under_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guess_payoff_round',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='model_payoff_round',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
