# Generated by Django 2.2.12 on 2022-02-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_practice_game', '0006_auto_20220202_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='guess_payoff_round',
        ),
    ]
