# Generated by Django 2.2.12 on 2022-02-25 17:20

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlh10_practice_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Vlh10_practice_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vlh10_practice_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Vlh10_practice_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('initial_opinion', otree.db.models.FloatField(null=True)),
                ('opinion_last_round', otree.db.models.FloatField(null=True)),
                ('opinion_this_round', otree.db.models.FloatField(blank=True, null=True)),
                ('observed_opinion_player1', otree.db.models.FloatField(null=True)),
                ('observed_opinion_player2', otree.db.models.FloatField(null=True)),
                ('observed_id_player1', otree.db.models.IntegerField(null=True)),
                ('observed_id_player2', otree.db.models.IntegerField(null=True)),
                ('if_connect_player1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 1?')),
                ('if_connect_player2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 2?')),
                ('num_neighbors', otree.db.models.IntegerField(default=0, null=True)),
                ('disconnect_with_player1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('disconnect_with_player2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('if_miss_neighbor', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True)),
                ('if_miss_opinion', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True)),
                ('game_payoff', otree.db.models.CurrencyField(null=True)),
                ('actual_payoff_round', otree.db.models.CurrencyField(null=True)),
                ('model_payoff_round', otree.db.models.CurrencyField(null=True)),
                ('timeout_choose_neighbors', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True)),
                ('timeout_update_opinion', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True)),
                ('neighbors_id_set', otree.db.models.LongStringField(null=True)),
                ('neighbors_opinion_set', otree.db.models.LongStringField(null=True)),
                ('neighbor_opinion_1', otree.db.models.FloatField(null=True)),
                ('neighbor_opinion_2', otree.db.models.FloatField(null=True)),
                ('neighbor_opinion_3', otree.db.models.FloatField(null=True)),
                ('neighbor_opinion_4', otree.db.models.FloatField(null=True)),
                ('neighbor_opinion_5', otree.db.models.FloatField(null=True)),
                ('neighbor_opinion_6', otree.db.models.FloatField(null=True)),
                ('neighbor_opinion_7', otree.db.models.FloatField(null=True)),
                ('neighbor_opinion_8', otree.db.models.FloatField(null=True)),
                ('neighbors_opinion_guess_set', otree.db.models.LongStringField(null=True)),
                ('update_neighbor_opinion_1', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('update_neighbor_opinion_2', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('update_neighbor_opinion_3', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('update_neighbor_opinion_4', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('update_neighbor_opinion_5', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('update_neighbor_opinion_6', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('update_neighbor_opinion_7', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('update_neighbor_opinion_8', otree.db.models.IntegerField(blank=True, null=True, verbose_name='')),
                ('neighbors_actual_opinion_set', otree.db.models.LongStringField(null=True)),
                ('actual_opinion_neighbor_1', otree.db.models.FloatField(null=True)),
                ('actual_opinion_neighbor_2', otree.db.models.FloatField(null=True)),
                ('actual_opinion_neighbor_3', otree.db.models.FloatField(null=True)),
                ('actual_opinion_neighbor_4', otree.db.models.FloatField(null=True)),
                ('actual_opinion_neighbor_5', otree.db.models.FloatField(null=True)),
                ('actual_opinion_neighbor_6', otree.db.models.FloatField(null=True)),
                ('actual_opinion_neighbor_7', otree.db.models.FloatField(null=True)),
                ('actual_opinion_neighbor_8', otree.db.models.FloatField(null=True)),
                ('disconnect_with_neighbor_1', otree.db.models.IntegerField(blank=True, null=True)),
                ('disconnect_with_neighbor_2', otree.db.models.IntegerField(blank=True, null=True)),
                ('disconnect_with_neighbor_3', otree.db.models.IntegerField(blank=True, null=True)),
                ('disconnect_with_neighbor_4', otree.db.models.IntegerField(blank=True, null=True)),
                ('disconnect_with_neighbor_5', otree.db.models.IntegerField(blank=True, null=True)),
                ('disconnect_with_neighbor_6', otree.db.models.IntegerField(blank=True, null=True)),
                ('disconnect_with_neighbor_7', otree.db.models.IntegerField(blank=True, null=True)),
                ('disconnect_with_neighbor_8', otree.db.models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vlh10_practice.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlh10_practice_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlh10_practice_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vlh10_practice.Subsession')),
            ],
            options={
                'db_table': 'Vlh10_practice_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vlh10_practice.Subsession'),
        ),
    ]
