# Generated by Django 2.2.12 on 2022-02-25 05:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Vlh10_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exchange_rate',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
