# Generated by Django 2.2.12 on 2022-02-03 03:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_FhH10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='model_payoff_round',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_payoff_experiment_dollar',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
