# Generated by Django 2.2.12 on 2021-06-17 05:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0002_auto_20210616_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='observed_player1',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='observed_player2',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
