# Generated by Django 2.2.12 on 2021-06-17 17:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0003_auto_20210616_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='if_connect_player1',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='if_connect_player2',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
