# Generated by Django 2.2.12 on 2021-06-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0006_auto_20210620_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='if_connect_player1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='if_connect_player2',
        ),
    ]
