# Generated by Django 2.2.12 on 2021-06-22 03:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0007_auto_20210621_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='if_connect_player1',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 1?'),
        ),
        migrations.AddField(
            model_name='player',
            name='if_connect_player2',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 2?'),
        ),
    ]
