# Generated by Django 2.2.12 on 2021-06-23 05:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0010_player_num_neighbors'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='disconnect_with_player1',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='disconnect_with_player2',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
