# Generated by Django 2.2.12 on 2021-06-25 17:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0011_auto_20210622_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opinion_this_round',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Please update your opinion in this round'),
        ),
    ]
