# Generated by Django 2.2.12 on 2021-06-25 19:26

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0018_auto_20210625_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='initial_opinion',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='observed_opinion_player1',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='observed_opinion_player2',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='opinion_last_round',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='opinion_this_round',
            field=otree.db.models.DecimalField(decimal_places=2, help_text='Note: please fill in a number between 0 and 1 with 2-digit decimals.', max_digits=3, null=True, verbose_name='Please update your opinion in this round'),
        ),
    ]
