# Generated by Django 2.2.12 on 2021-06-25 19:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0019_auto_20210625_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opinion_this_round',
            field=otree.db.models.DecimalField(decimal_places=2, help_text='Note: please fill in a 2- number between 0 and 1 with 2-digit decimals.', max_digits=3, null=True, verbose_name='Please update your opinion in this round'),
        ),
    ]
