# Generated by Django 2.2.12 on 2021-06-25 23:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0024_auto_20210625_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='if_miss_neighbor',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='if_miss_opinion',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0, null=True),
        ),
    ]
