# Generated by Django 2.2.12 on 2021-06-26 22:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0029_auto_20210626_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opinion_this_round',
            field=otree.db.models.FloatField(blank=True, help_text='Note: please fill in a number between 0 and 1', null=True, verbose_name='Please update your opinion in this round'),
        ),
    ]
