# Generated by Django 2.2.12 on 2021-06-26 22:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0030_auto_20210626_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='if_connect_player1',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 1?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='if_connect_player2',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to connect with Player 2?'),
        ),
    ]
